### ISSUE TITLE
report of copyright illegal

### ISSUE THREAD

**Issue by darallium** [tsukumijima/youtube-live-chat-flow#2]
Your program has been forked and is being released as an extension to others by others without your permission.
He has published your extension under his own name.
I encourage you to file a protest complaint.

Forked: https://github.com/subdiox/youtube-live-chat-flow
Store url: https://chrome.google.com/webstore/detail/flow-chat-for-youtube-liv/elfdpkmfllnhhgnicaaeacbilcallpbd

PS: I saw your past Issue. I support having it removed as it is also against your original intention.

**Comment by tsukumijima** [comment]
I have only mirrored this repository at the minimum level (I don't have the resources or motivation to improve the code), but considering that subdiox is maintaining the code, I don't think there's an issue with them releasing extensions.
